import type { Metadata } from "next"
import { Flex, Layout } from 'antd'
import { App } from '@/0_app/App'
import { Content } from 'antd/es/layout/layout'
import './global.css'
import Script from 'next/script';
import { Header } from '@/2_widgets/header'
import { HeaderProfile } from '@/2_widgets/me'
import { HeaderWallet } from '@/2_widgets/header/headerWallet'
import { BetaNotify } from '@/5_shared/ui/BetaNotify/BetaNotify'

const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || ''

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <App>
        <body>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
            strategy="afterInteractive"
          />
          <Script id="gtag-init" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
    
              gtag('config', '${GA_MEASUREMENT_ID}', {
                page_path: window.location.pathname,
              });
            `}
          </Script>
          <Layout>
            <Flex
              vertical
              style={{ height: '100vh' }}
            >
              <Header walletSlot={<HeaderWallet />} profileSlot={<HeaderProfile />} />
              <div style={{ height: '100%', overflow: 'auto' }}>
                {/* <BetaNotify /> */}
                <Content className="cont" style={{ height: '100%' }}>
                  {children}
                </Content>
              </div>
            </Flex>
          </Layout>
        </body>
      </App>
    </html>
  )
}
