import type { Metadata } from 'next';
import { Flex, Layout } from 'antd';
import { App } from '@/0_app/App';
import { Content } from 'antd/es/layout/layout';
import './global.css';
import Script from 'next/script';
import { Header } from '@/2_widgets/header';
import { HeaderProfile } from '@/2_widgets/me';
import { HeaderWallet } from '@/2_widgets/header/headerWallet';
import { BetaNotify } from '@/5_shared/ui/BetaNotify/BetaNotify';
import { GoogleAnalytics } from './GoogleAnalitycs';

const IS_DEV = process.env.NEXT_PUBLIC_DEV_MODE === 'true';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="icon"
                    href="/LB_No_BG_Favicon.png"
                    type="image/png"
                />
                {/* <link rel="icon" href="./assets/LB_No_BG_Favicon.png"></link> */}
            </head>
            <App>
                <body>
                    {!IS_DEV && <GoogleAnalytics />}
                    <Layout>
                        <Flex vertical style={{ height: '100vh' }}>
                            <Header
                                walletSlot={<HeaderWallet />}
                                profileSlot={<HeaderProfile />}
                            />
                            <div style={{ height: '100%', overflow: 'auto' }}>
                                {/* <BetaNotify /> */}
                                <Content
                                    className="cont"
                                    style={{ height: '100%' }}
                                >
                                    {children}
                                </Content>
                            </div>
                        </Flex>
                    </Layout>
                </body>
            </App>
        </html>
    );
}
